INSERT INTO public.province ("name",region_id) VALUES 
('Arica',1)
,('Parinacota',1)
,('Iquique',2)
,('El Tamarugal',2)
,('Antofagasta',3)
,('El Loa',3)
,('Tocopilla',3)
,('Chañaral',4)
,('Copiapó',4)
,('Huasco',4)
;
INSERT INTO public.province ("name",region_id) VALUES 
('Choapa',5)
,('Elqui',5)
,('Limarí',5)
,('Isla de Pascua',6)
,('Los Andes',6)
,('Petorca',6)
,('Quillota',6)
,('San Antonio',6)
,('San Felipe de Aconcagua',6)
,('Valparaiso',6)
;
INSERT INTO public.province ("name",region_id) VALUES 
('Chacabuco',7)
,('Cordillera',7)
,('Maipo',7)
,('Melipilla',7)
,('Santiago',7)
,('Talagante',7)
,('Cachapoal',8)
,('Cardenal Caro',8)
,('Colchagua',8)
,('Cauquenes',9)
;
INSERT INTO public.province ("name",region_id) VALUES 
('Curicó',9)
,('Linares',9)
,('Talca',9)
,('Arauco',10)
,('Bio Bío',10)
,('Concepción',10)
,('Ñuble',10)
,('Cautín',11)
,('Malleco',11)
,('Valdivia',12)
;
INSERT INTO public.province ("name",region_id) VALUES 
('Ranco',12)
,('Chiloé',13)
,('Llanquihue',13)
,('Osorno',13)
,('Palena',13)
,('Aisén',14)
,('Capitán Prat',14)
,('Coihaique',14)
,('General Carrera',14)
,('Antártica Chilena',15)
;
INSERT INTO public.province ("name",region_id) VALUES 
('Magallanes',15)
,('Tierra del Fuego',15)
,('Última Esperanza',15)
;